
const Map<String, String> en = {
  "error_wrong": "Something went wrong try again later",
  "error_wrong_admin": "Something went wrong, contact admin",
  "required_field": "field is required",
  "error_server": "error connecting to server please try again",
  "success_login": "login successful",
  "turn_wifi": "Turn on Wi-Fi",
  "help_center": "How To..",
  "favorites": "Favorites",
  "completed_success": "Completed successfully",
  "error_connection": "No internet connection. Make sure Wi-Fi or cellular data is turned on, then try again",
  "how_center": "Help",
  "how_change_track": "Change the Playback Speed",
  "how_download": "Download a Service to the App",
  "how_ply_album": "Play a Service",
  "how_favourite": "Bookmark a Service",
  "how_skip": "Skip Forward/Back 15 Seconds in a Service",
  "how_sleep": "Apply a Sleep Timer",
  "how_resume": "Resume Where you Left off in Service",
  "how_search": "Search the Services/Subjects Tab",
  "privacy_page": "Privacy Policy",
  "name_app": "NA 0826",
  "msg_exit_app": "Are you sure you want to Exit?",
  "no": "NO",
  "yes": "YES",
  "exit_app": "Exit App",

};